<?php
/**
 * PaymentsApi
 * PHP version 7.2
 *
 * @category Class
 * @package  AllegroApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Allegro REST API
 *
 * https://developer.allegro.pl/about  Documentation is generated from [this](https://developer.allegro.pl/swagger.yaml) OpenAPI 3.0 specification file.
 *
 * The version of the OpenAPI document: latest
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace AllegroApi\Api;

use AllegroApi\Configuration;
use AllegroApi\DebugPlugin;
use AllegroApi\Exception\ApiException;
use AllegroApi\HeaderSelector;
use AllegroApi\ObjectSerializer;
use GuzzleHttp\Psr7\MultipartStream;
use Http\Client\Common\Plugin\ErrorPlugin;
use Http\Client\Common\Plugin\RedirectPlugin;
use Http\Client\Common\PluginClient;
use Http\Client\Common\PluginClientFactory;
use Http\Client\Exception\HttpException;
use Http\Client\HttpAsyncClient;
use Http\Discovery\HttpAsyncClientDiscovery;
use Http\Discovery\Psr17FactoryDiscovery;
use Http\Discovery\Psr18ClientDiscovery;
use Http\Message\RequestFactory;
use Http\Promise\Promise;
use Psr\Http\Client\ClientExceptionInterface;
use Psr\Http\Client\ClientInterface;
use Psr\Http\Message\RequestFactoryInterface;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\StreamFactoryInterface;
use Psr\Http\Message\UriFactoryInterface;
use Psr\Http\Message\UriInterface;

use function sprintf;

/**
 * PaymentsApi Class Doc Comment
 *
 * @category Class
 * @package  AllegroApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PaymentsApi
{
    /**
     * @var PluginClient
     */
    protected $httpClient;

    /**
     * @var PluginClient
     */
    protected $httpAsyncClient;

    /**
     * @var UriFactoryInterface
     */
    protected $uriFactory;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @var RequestFactoryInterface
     */
    protected $requestFactory;

    /**
     * @var StreamFactoryInterface
     */
    protected $streamFactory;

    public function __construct(
        ClientInterface $httpClient = null,
        Configuration $config = null,
        HttpAsyncClient $httpAsyncClient = null,
        UriFactoryInterface $uriFactory = null,
        RequestFactoryInterface $requestFactory = null,
        StreamFactoryInterface $streamFactory = null,
        HeaderSelector $selector = null,
        ?array $plugins = null,
        $hostIndex = 0
    ) {
        $this->config = $config ?? (new Configuration())->setHost('https://api.allegro.pl');
        $this->requestFactory = $requestFactory ?? Psr17FactoryDiscovery::findRequestFactory();
        $this->streamFactory = $streamFactory ?? Psr17FactoryDiscovery::findStreamFactory();

        $plugins = $plugins ?? [
            new RedirectPlugin(['strict' => true]),
            new ErrorPlugin(),
        ];

        if ($this->config->getDebug()) {
            $plugins[] = new DebugPlugin(fopen($this->config->getDebugFile(), 'ab'));
        }

        $this->httpClient = (new PluginClientFactory())->createClient(
            $httpClient ?? Psr18ClientDiscovery::find(),
            $plugins
        );

        $this->httpAsyncClient = (new PluginClientFactory())->createClient(
            $httpAsyncClient ?? HttpAsyncClientDiscovery::find(),
            $plugins
        );

        $this->uriFactory = $uriFactory ?? Psr17FactoryDiscovery::findUriFactory();

        $this->headerSelector = $selector ?? new HeaderSelector();

        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getPaymentsOperationHistory
     *
     * Payment operations history
     *
     * @param  string $wallet_type Type of the wallet: * AVAILABLE - operations available for payout. * WAITING - operations temporarily suspended for payout. (optional, default to 'AVAILABLE')
     * @param  string $wallet_payment_operator Payment operator: * PAYU - operations processed by PAYU operator. * P24 - operations processed by PRZELEWY24 operator. * AF - operations processed by Allegro Finance operator. (optional)
     * @param  string $payment_id The payment ID. (optional)
     * @param  string $participant_login Login of the participant. In case of REFUND_INCREASE operation this is the login of the seller, in other cases, of the buyer. (optional)
     * @param  \DateTime $occurred_at_gte The minimum date and time of operation occurrence in ISO 8601 format. (optional)
     * @param  \DateTime $occurred_at_lte The maximum date and time of operation occurrence in ISO 8601 format. (optional)
     * @param  string[] $group Group of operation types: * INCOME - CONTRIBUTION, SURCHARGE, CORRECTION, DEDUCTION_INCREASE, COMPENSATION. * OUTCOME - PAYOUT, PAYOUT_CANCEL, DEDUCTION_CHARGE. * REFUND - REFUND_CHARGE, REFUND_CANCEL, REFUND_INCREASE, CORRECTION. * BLOCKADES - BLOCKADE, BLOCKADE_RELEASE. (optional)
     * @param  string $marketplace_id The marketplace ID where operation was made. When the parameter is omitted, searches for operations with all marketplaces. Note, that there are operations not assigned to any marketplace. (optional)
     * @param  string $currency Currency of the operations. (optional)
     * @param  int $limit Number of returned operations. (optional, default to 50)
     * @param  int $offset Index of the first returned payment operation from all search results. (optional, default to 0)
     *
     *@throws \AllegroApi\Exception\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return |\AllegroApi\Model\PaymentOperations|\AllegroApi\Model\ErrorsHolder
     */
    public function getPaymentsOperationHistory($wallet_type = 'AVAILABLE', $wallet_payment_operator = null, $payment_id = null, $participant_login = null, $occurred_at_gte = null, $occurred_at_lte = null, $group = null, $marketplace_id = null, $currency = null, $limit = 50, $offset = 0)
    {
        [$response] = $this->getPaymentsOperationHistoryWithHttpInfo($wallet_type, $wallet_payment_operator, $payment_id, $participant_login, $occurred_at_gte, $occurred_at_lte, $group, $marketplace_id, $currency, $limit, $offset);
        return $response;
    }

    /**
     * Operation getPaymentsOperationHistoryWithHttpInfo
     *
     * Payment operations history
     *
     * @param  string $wallet_type Type of the wallet: * AVAILABLE - operations available for payout. * WAITING - operations temporarily suspended for payout. (optional, default to 'AVAILABLE')
     * @param  string $wallet_payment_operator Payment operator: * PAYU - operations processed by PAYU operator. * P24 - operations processed by PRZELEWY24 operator. * AF - operations processed by Allegro Finance operator. (optional)
     * @param  string $payment_id The payment ID. (optional)
     * @param  string $participant_login Login of the participant. In case of REFUND_INCREASE operation this is the login of the seller, in other cases, of the buyer. (optional)
     * @param  \DateTime $occurred_at_gte The minimum date and time of operation occurrence in ISO 8601 format. (optional)
     * @param  \DateTime $occurred_at_lte The maximum date and time of operation occurrence in ISO 8601 format. (optional)
     * @param  string[] $group Group of operation types: * INCOME - CONTRIBUTION, SURCHARGE, CORRECTION, DEDUCTION_INCREASE, COMPENSATION. * OUTCOME - PAYOUT, PAYOUT_CANCEL, DEDUCTION_CHARGE. * REFUND - REFUND_CHARGE, REFUND_CANCEL, REFUND_INCREASE, CORRECTION. * BLOCKADES - BLOCKADE, BLOCKADE_RELEASE. (optional)
     * @param  string $marketplace_id The marketplace ID where operation was made. When the parameter is omitted, searches for operations with all marketplaces. Note, that there are operations not assigned to any marketplace. (optional)
     * @param  string $currency Currency of the operations. (optional)
     * @param  int $limit Number of returned operations. (optional, default to 50)
     * @param  int $offset Index of the first returned payment operation from all search results. (optional, default to 0)
     *
     *@throws \AllegroApi\Exception\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of |\AllegroApi\Model\PaymentOperations|\AllegroApi\Model\ErrorsHolder, HTTP status code, HTTP response headers (array of strings)
     */
    public function getPaymentsOperationHistoryWithHttpInfo($wallet_type = 'AVAILABLE', $wallet_payment_operator = null, $payment_id = null, $participant_login = null, $occurred_at_gte = null, $occurred_at_lte = null, $group = null, $marketplace_id = null, $currency = null, $limit = 50, $offset = 0)
    {
        $request = $this->getPaymentsOperationHistoryRequest($wallet_type, $wallet_payment_operator, $payment_id, $participant_login, $occurred_at_gte, $occurred_at_lte, $group, $marketplace_id, $currency, $limit, $offset);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    if ('\AllegroApi\Model\PaymentOperations' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\AllegroApi\Model\PaymentOperations', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 422:
                    if ('\AllegroApi\Model\ErrorsHolder' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\AllegroApi\Model\ErrorsHolder', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\AllegroApi\Model\PaymentOperations';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\AllegroApi\Model\PaymentOperations',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\AllegroApi\Model\ErrorsHolder',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getPaymentsOperationHistoryAsync
     *
     * Payment operations history
     *
     * @param  string $wallet_type Type of the wallet: * AVAILABLE - operations available for payout. * WAITING - operations temporarily suspended for payout. (optional, default to 'AVAILABLE')
     * @param  string $wallet_payment_operator Payment operator: * PAYU - operations processed by PAYU operator. * P24 - operations processed by PRZELEWY24 operator. * AF - operations processed by Allegro Finance operator. (optional)
     * @param  string $payment_id The payment ID. (optional)
     * @param  string $participant_login Login of the participant. In case of REFUND_INCREASE operation this is the login of the seller, in other cases, of the buyer. (optional)
     * @param  \DateTime $occurred_at_gte The minimum date and time of operation occurrence in ISO 8601 format. (optional)
     * @param  \DateTime $occurred_at_lte The maximum date and time of operation occurrence in ISO 8601 format. (optional)
     * @param  string[] $group Group of operation types: * INCOME - CONTRIBUTION, SURCHARGE, CORRECTION, DEDUCTION_INCREASE, COMPENSATION. * OUTCOME - PAYOUT, PAYOUT_CANCEL, DEDUCTION_CHARGE. * REFUND - REFUND_CHARGE, REFUND_CANCEL, REFUND_INCREASE, CORRECTION. * BLOCKADES - BLOCKADE, BLOCKADE_RELEASE. (optional)
     * @param  string $marketplace_id The marketplace ID where operation was made. When the parameter is omitted, searches for operations with all marketplaces. Note, that there are operations not assigned to any marketplace. (optional)
     * @param  string $currency Currency of the operations. (optional)
     * @param  int $limit Number of returned operations. (optional, default to 50)
     * @param  int $offset Index of the first returned payment operation from all search results. (optional, default to 0)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function getPaymentsOperationHistoryAsync($wallet_type = 'AVAILABLE', $wallet_payment_operator = null, $payment_id = null, $participant_login = null, $occurred_at_gte = null, $occurred_at_lte = null, $group = null, $marketplace_id = null, $currency = null, $limit = 50, $offset = 0)
    {
        return $this->getPaymentsOperationHistoryAsyncWithHttpInfo($wallet_type, $wallet_payment_operator, $payment_id, $participant_login, $occurred_at_gte, $occurred_at_lte, $group, $marketplace_id, $currency, $limit, $offset)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getPaymentsOperationHistoryAsyncWithHttpInfo
     *
     * Payment operations history
     *
     * @param  string $wallet_type Type of the wallet: * AVAILABLE - operations available for payout. * WAITING - operations temporarily suspended for payout. (optional, default to 'AVAILABLE')
     * @param  string $wallet_payment_operator Payment operator: * PAYU - operations processed by PAYU operator. * P24 - operations processed by PRZELEWY24 operator. * AF - operations processed by Allegro Finance operator. (optional)
     * @param  string $payment_id The payment ID. (optional)
     * @param  string $participant_login Login of the participant. In case of REFUND_INCREASE operation this is the login of the seller, in other cases, of the buyer. (optional)
     * @param  \DateTime $occurred_at_gte The minimum date and time of operation occurrence in ISO 8601 format. (optional)
     * @param  \DateTime $occurred_at_lte The maximum date and time of operation occurrence in ISO 8601 format. (optional)
     * @param  string[] $group Group of operation types: * INCOME - CONTRIBUTION, SURCHARGE, CORRECTION, DEDUCTION_INCREASE, COMPENSATION. * OUTCOME - PAYOUT, PAYOUT_CANCEL, DEDUCTION_CHARGE. * REFUND - REFUND_CHARGE, REFUND_CANCEL, REFUND_INCREASE, CORRECTION. * BLOCKADES - BLOCKADE, BLOCKADE_RELEASE. (optional)
     * @param  string $marketplace_id The marketplace ID where operation was made. When the parameter is omitted, searches for operations with all marketplaces. Note, that there are operations not assigned to any marketplace. (optional)
     * @param  string $currency Currency of the operations. (optional)
     * @param  int $limit Number of returned operations. (optional, default to 50)
     * @param  int $offset Index of the first returned payment operation from all search results. (optional, default to 0)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function getPaymentsOperationHistoryAsyncWithHttpInfo($wallet_type = 'AVAILABLE', $wallet_payment_operator = null, $payment_id = null, $participant_login = null, $occurred_at_gte = null, $occurred_at_lte = null, $group = null, $marketplace_id = null, $currency = null, $limit = 50, $offset = 0)
    {
        $returnType = '\AllegroApi\Model\PaymentOperations';
        $request = $this->getPaymentsOperationHistoryRequest($wallet_type, $wallet_payment_operator, $payment_id, $participant_login, $occurred_at_gte, $occurred_at_lte, $group, $marketplace_id, $currency, $limit, $offset);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function (HttpException $exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $exception->getRequest(),
                        $exception->getResponse(),
                        $exception
                    );
                }
            );
    }

    /**
     * Create request for operation 'getPaymentsOperationHistory'
     *
     * @param  string $wallet_type Type of the wallet: * AVAILABLE - operations available for payout. * WAITING - operations temporarily suspended for payout. (optional, default to 'AVAILABLE')
     * @param  string $wallet_payment_operator Payment operator: * PAYU - operations processed by PAYU operator. * P24 - operations processed by PRZELEWY24 operator. * AF - operations processed by Allegro Finance operator. (optional)
     * @param  string $payment_id The payment ID. (optional)
     * @param  string $participant_login Login of the participant. In case of REFUND_INCREASE operation this is the login of the seller, in other cases, of the buyer. (optional)
     * @param  \DateTime $occurred_at_gte The minimum date and time of operation occurrence in ISO 8601 format. (optional)
     * @param  \DateTime $occurred_at_lte The maximum date and time of operation occurrence in ISO 8601 format. (optional)
     * @param  string[] $group Group of operation types: * INCOME - CONTRIBUTION, SURCHARGE, CORRECTION, DEDUCTION_INCREASE, COMPENSATION. * OUTCOME - PAYOUT, PAYOUT_CANCEL, DEDUCTION_CHARGE. * REFUND - REFUND_CHARGE, REFUND_CANCEL, REFUND_INCREASE, CORRECTION. * BLOCKADES - BLOCKADE, BLOCKADE_RELEASE. (optional)
     * @param  string $marketplace_id The marketplace ID where operation was made. When the parameter is omitted, searches for operations with all marketplaces. Note, that there are operations not assigned to any marketplace. (optional)
     * @param  string $currency Currency of the operations. (optional)
     * @param  int $limit Number of returned operations. (optional, default to 50)
     * @param  int $offset Index of the first returned payment operation from all search results. (optional, default to 0)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function getPaymentsOperationHistoryRequest($wallet_type = 'AVAILABLE', $wallet_payment_operator = null, $payment_id = null, $participant_login = null, $occurred_at_gte = null, $occurred_at_lte = null, $group = null, $marketplace_id = null, $currency = null, $limit = 50, $offset = 0)
    {
        if ($limit !== null && $limit > 50) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling PaymentsApi.getPaymentsOperationHistory, must be smaller than or equal to 50.');
        }
        if ($limit !== null && $limit < 1) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling PaymentsApi.getPaymentsOperationHistory, must be bigger than or equal to 1.');
        }

        if ($offset !== null && $offset > 10000) {
            throw new \InvalidArgumentException('invalid value for "$offset" when calling PaymentsApi.getPaymentsOperationHistory, must be smaller than or equal to 10000.');
        }
        if ($offset !== null && $offset < 0) {
            throw new \InvalidArgumentException('invalid value for "$offset" when calling PaymentsApi.getPaymentsOperationHistory, must be bigger than or equal to 0.');
        }

        $resourcePath = '/payments/payment-operations';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;

        // query params
        if ($wallet_type !== null) {
            if('form' === 'form' && is_array($wallet_type)) {
                foreach($wallet_type as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['wallet.type'] = $wallet_type;
            }
        }
        // query params
        if ($wallet_payment_operator !== null) {
            if('form' === 'form' && is_array($wallet_payment_operator)) {
                foreach($wallet_payment_operator as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['wallet.paymentOperator'] = $wallet_payment_operator;
            }
        }
        // query params
        if ($payment_id !== null) {
            if('form' === 'form' && is_array($payment_id)) {
                foreach($payment_id as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['payment.id'] = $payment_id;
            }
        }
        // query params
        if ($participant_login !== null) {
            if('form' === 'form' && is_array($participant_login)) {
                foreach($participant_login as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['participant.login'] = $participant_login;
            }
        }
        // query params
        if ($occurred_at_gte !== null) {
            if('form' === 'form' && is_array($occurred_at_gte)) {
                foreach($occurred_at_gte as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['occurredAt.gte'] = $occurred_at_gte;
            }
        }
        // query params
        if ($occurred_at_lte !== null) {
            if('form' === 'form' && is_array($occurred_at_lte)) {
                foreach($occurred_at_lte as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['occurredAt.lte'] = $occurred_at_lte;
            }
        }
        // query params
        if ($group !== null) {
            if('form' === 'form' && is_array($group)) {
                foreach($group as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['group'] = $group;
            }
        }
        // query params
        if ($marketplace_id !== null) {
            if('form' === 'form' && is_array($marketplace_id)) {
                foreach($marketplace_id as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['marketplaceId'] = $marketplace_id;
            }
        }
        // query params
        if ($currency !== null) {
            if('form' === 'form' && is_array($currency)) {
                foreach($currency as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['currency'] = $currency;
            }
        }
        // query params
        if ($limit !== null) {
            if('form' === 'form' && is_array($limit)) {
                foreach($limit as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['limit'] = $limit;
            }
        }
        // query params
        if ($offset !== null) {
            if('form' === 'form' && is_array($offset)) {
                foreach($offset as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['offset'] = $offset;
            }
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/vnd.allegro.public.v1+json'],
            '',
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('GET', $uri, $headers, $httpBody);
    }

    /**
     * Operation getRefundedPayments
     *
     * Get a list of refunded payments
     *
     * @param  int $limit Number of returned operations. (optional, default to 50)
     * @param  int $offset Index of the first returned payment operation from all search results. (optional, default to 0)
     * @param  string $id ID of the refund. (optional)
     * @param  string $payment_id ID of the payment. (optional)
     * @param  \DateTime $occurred_at_gte Minimum date and time when the refund occurred provided in ISO 8601 format. (optional)
     * @param  \DateTime $occurred_at_lte Maximum date and time when the refund occurred provided in ISO 8601 format. (optional)
     * @param  string[] $status Current status of payment refund. (optional)
     *
     *@throws \AllegroApi\Exception\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \AllegroApi\Model\GetRefundedPayments200Response|\AllegroApi\Model\AuthError|\AllegroApi\Model\GetOfferSmartClassificationGET403Response|\AllegroApi\Model\ErrorsHolder
     */
    public function getRefundedPayments($limit = 50, $offset = 0, $id = null, $payment_id = null, $occurred_at_gte = null, $occurred_at_lte = null, $status = null)
    {
        [$response] = $this->getRefundedPaymentsWithHttpInfo($limit, $offset, $id, $payment_id, $occurred_at_gte, $occurred_at_lte, $status);
        return $response;
    }

    /**
     * Operation getRefundedPaymentsWithHttpInfo
     *
     * Get a list of refunded payments
     *
     * @param  int $limit Number of returned operations. (optional, default to 50)
     * @param  int $offset Index of the first returned payment operation from all search results. (optional, default to 0)
     * @param  string $id ID of the refund. (optional)
     * @param  string $payment_id ID of the payment. (optional)
     * @param  \DateTime $occurred_at_gte Minimum date and time when the refund occurred provided in ISO 8601 format. (optional)
     * @param  \DateTime $occurred_at_lte Maximum date and time when the refund occurred provided in ISO 8601 format. (optional)
     * @param  string[] $status Current status of payment refund. (optional)
     *
     *@throws \AllegroApi\Exception\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \AllegroApi\Model\GetRefundedPayments200Response|\AllegroApi\Model\AuthError|\AllegroApi\Model\GetOfferSmartClassificationGET403Response|\AllegroApi\Model\ErrorsHolder, HTTP status code, HTTP response headers (array of strings)
     */
    public function getRefundedPaymentsWithHttpInfo($limit = 50, $offset = 0, $id = null, $payment_id = null, $occurred_at_gte = null, $occurred_at_lte = null, $status = null)
    {
        $request = $this->getRefundedPaymentsRequest($limit, $offset, $id, $payment_id, $occurred_at_gte, $occurred_at_lte, $status);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    if ('\AllegroApi\Model\GetRefundedPayments200Response' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\AllegroApi\Model\GetRefundedPayments200Response', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\AllegroApi\Model\AuthError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\AllegroApi\Model\AuthError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 403:
                    if ('\AllegroApi\Model\GetOfferSmartClassificationGET403Response' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\AllegroApi\Model\GetOfferSmartClassificationGET403Response', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 422:
                    if ('\AllegroApi\Model\ErrorsHolder' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\AllegroApi\Model\ErrorsHolder', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\AllegroApi\Model\GetRefundedPayments200Response';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\AllegroApi\Model\GetRefundedPayments200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\AllegroApi\Model\AuthError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\AllegroApi\Model\GetOfferSmartClassificationGET403Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\AllegroApi\Model\ErrorsHolder',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getRefundedPaymentsAsync
     *
     * Get a list of refunded payments
     *
     * @param  int $limit Number of returned operations. (optional, default to 50)
     * @param  int $offset Index of the first returned payment operation from all search results. (optional, default to 0)
     * @param  string $id ID of the refund. (optional)
     * @param  string $payment_id ID of the payment. (optional)
     * @param  \DateTime $occurred_at_gte Minimum date and time when the refund occurred provided in ISO 8601 format. (optional)
     * @param  \DateTime $occurred_at_lte Maximum date and time when the refund occurred provided in ISO 8601 format. (optional)
     * @param  string[] $status Current status of payment refund. (optional)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function getRefundedPaymentsAsync($limit = 50, $offset = 0, $id = null, $payment_id = null, $occurred_at_gte = null, $occurred_at_lte = null, $status = null)
    {
        return $this->getRefundedPaymentsAsyncWithHttpInfo($limit, $offset, $id, $payment_id, $occurred_at_gte, $occurred_at_lte, $status)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getRefundedPaymentsAsyncWithHttpInfo
     *
     * Get a list of refunded payments
     *
     * @param  int $limit Number of returned operations. (optional, default to 50)
     * @param  int $offset Index of the first returned payment operation from all search results. (optional, default to 0)
     * @param  string $id ID of the refund. (optional)
     * @param  string $payment_id ID of the payment. (optional)
     * @param  \DateTime $occurred_at_gte Minimum date and time when the refund occurred provided in ISO 8601 format. (optional)
     * @param  \DateTime $occurred_at_lte Maximum date and time when the refund occurred provided in ISO 8601 format. (optional)
     * @param  string[] $status Current status of payment refund. (optional)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function getRefundedPaymentsAsyncWithHttpInfo($limit = 50, $offset = 0, $id = null, $payment_id = null, $occurred_at_gte = null, $occurred_at_lte = null, $status = null)
    {
        $returnType = '\AllegroApi\Model\GetRefundedPayments200Response';
        $request = $this->getRefundedPaymentsRequest($limit, $offset, $id, $payment_id, $occurred_at_gte, $occurred_at_lte, $status);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function (HttpException $exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $exception->getRequest(),
                        $exception->getResponse(),
                        $exception
                    );
                }
            );
    }

    /**
     * Create request for operation 'getRefundedPayments'
     *
     * @param  int $limit Number of returned operations. (optional, default to 50)
     * @param  int $offset Index of the first returned payment operation from all search results. (optional, default to 0)
     * @param  string $id ID of the refund. (optional)
     * @param  string $payment_id ID of the payment. (optional)
     * @param  \DateTime $occurred_at_gte Minimum date and time when the refund occurred provided in ISO 8601 format. (optional)
     * @param  \DateTime $occurred_at_lte Maximum date and time when the refund occurred provided in ISO 8601 format. (optional)
     * @param  string[] $status Current status of payment refund. (optional)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function getRefundedPaymentsRequest($limit = 50, $offset = 0, $id = null, $payment_id = null, $occurred_at_gte = null, $occurred_at_lte = null, $status = null)
    {
        if ($limit !== null && $limit > 100) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling PaymentsApi.getRefundedPayments, must be smaller than or equal to 100.');
        }
        if ($limit !== null && $limit < 1) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling PaymentsApi.getRefundedPayments, must be bigger than or equal to 1.');
        }

        if ($offset !== null && $offset < 0) {
            throw new \InvalidArgumentException('invalid value for "$offset" when calling PaymentsApi.getRefundedPayments, must be bigger than or equal to 0.');
        }

        $resourcePath = '/payments/refunds';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;

        // query params
        if ($limit !== null) {
            if('form' === 'form' && is_array($limit)) {
                foreach($limit as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['limit'] = $limit;
            }
        }
        // query params
        if ($offset !== null) {
            if('form' === 'form' && is_array($offset)) {
                foreach($offset as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['offset'] = $offset;
            }
        }
        // query params
        if ($id !== null) {
            if('form' === 'form' && is_array($id)) {
                foreach($id as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['id'] = $id;
            }
        }
        // query params
        if ($payment_id !== null) {
            if('form' === 'form' && is_array($payment_id)) {
                foreach($payment_id as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['payment.id'] = $payment_id;
            }
        }
        // query params
        if ($occurred_at_gte !== null) {
            if('form' === 'form' && is_array($occurred_at_gte)) {
                foreach($occurred_at_gte as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['occurredAt.gte'] = $occurred_at_gte;
            }
        }
        // query params
        if ($occurred_at_lte !== null) {
            if('form' === 'form' && is_array($occurred_at_lte)) {
                foreach($occurred_at_lte as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['occurredAt.lte'] = $occurred_at_lte;
            }
        }
        // query params
        if ($status !== null) {
            if('form' === 'form' && is_array($status)) {
                foreach($status as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['status'] = $status;
            }
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/vnd.allegro.public.v1+json'],
            '',
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('GET', $uri, $headers, $httpBody);
    }

    /**
     * Operation initiateRefund
     *
     * Initiate a refund of a payment
     *
     * @param  \AllegroApi\Model\InitializeRefund $initialize_refund initialize_refund (optional)
     *
     *@throws \InvalidArgumentException
     * @throws \AllegroApi\Exception\ApiException on non-2xx response
     * @return \AllegroApi\Model\RefundDetails|\AllegroApi\Model\ErrorsHolder|\AllegroApi\Model\AuthError|\AllegroApi\Model\ErrorsHolder|\AllegroApi\Model\GetOfferSmartClassificationGET403Response|\AllegroApi\Model\ErrorsHolder
     */
    public function initiateRefund($initialize_refund = null)
    {
        [$response] = $this->initiateRefundWithHttpInfo($initialize_refund);
        return $response;
    }

    /**
     * Operation initiateRefundWithHttpInfo
     *
     * Initiate a refund of a payment
     *
     * @param  \AllegroApi\Model\InitializeRefund $initialize_refund (optional)
     *
     *@throws \InvalidArgumentException
     * @throws \AllegroApi\Exception\ApiException on non-2xx response
     * @return array of \AllegroApi\Model\RefundDetails|\AllegroApi\Model\ErrorsHolder|\AllegroApi\Model\AuthError|\AllegroApi\Model\ErrorsHolder|\AllegroApi\Model\GetOfferSmartClassificationGET403Response|\AllegroApi\Model\ErrorsHolder, HTTP status code, HTTP response headers (array of strings)
     */
    public function initiateRefundWithHttpInfo($initialize_refund = null)
    {
        $request = $this->initiateRefundRequest($initialize_refund);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    if ('\AllegroApi\Model\RefundDetails' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\AllegroApi\Model\RefundDetails', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\AllegroApi\Model\ErrorsHolder' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\AllegroApi\Model\ErrorsHolder', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\AllegroApi\Model\AuthError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\AllegroApi\Model\AuthError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 422:
                    if ('\AllegroApi\Model\ErrorsHolder' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\AllegroApi\Model\ErrorsHolder', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 403:
                    if ('\AllegroApi\Model\GetOfferSmartClassificationGET403Response' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\AllegroApi\Model\GetOfferSmartClassificationGET403Response', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 404:
                    if ('\AllegroApi\Model\ErrorsHolder' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\AllegroApi\Model\ErrorsHolder', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\AllegroApi\Model\RefundDetails';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\AllegroApi\Model\RefundDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\AllegroApi\Model\ErrorsHolder',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\AllegroApi\Model\AuthError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\AllegroApi\Model\ErrorsHolder',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\AllegroApi\Model\GetOfferSmartClassificationGET403Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\AllegroApi\Model\ErrorsHolder',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation initiateRefundAsync
     *
     * Initiate a refund of a payment
     *
     * @param  \AllegroApi\Model\InitializeRefund $initialize_refund (optional)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function initiateRefundAsync($initialize_refund = null)
    {
        return $this->initiateRefundAsyncWithHttpInfo($initialize_refund)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation initiateRefundAsyncWithHttpInfo
     *
     * Initiate a refund of a payment
     *
     * @param  \AllegroApi\Model\InitializeRefund $initialize_refund (optional)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function initiateRefundAsyncWithHttpInfo($initialize_refund = null)
    {
        $returnType = '\AllegroApi\Model\RefundDetails';
        $request = $this->initiateRefundRequest($initialize_refund);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function (HttpException $exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $exception->getRequest(),
                        $exception->getResponse(),
                        $exception
                    );
                }
            );
    }

    /**
     * Create request for operation 'initiateRefund'
     *
     * @param  \AllegroApi\Model\InitializeRefund $initialize_refund (optional)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function initiateRefundRequest($initialize_refund = null)
    {

        $resourcePath = '/payments/refunds';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;

        $headers = $this->headerSelector->selectHeaders(
            ['application/vnd.allegro.public.v1+json'],
            'application/vnd.allegro.public.v1+json',
            $multipart
        );

        // for model (json/xml)
        if (isset($initialize_refund)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = json_encode(ObjectSerializer::sanitizeForSerialization($initialize_refund));
            } else {
                $httpBody = $initialize_refund;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('POST', $uri, $headers, $httpBody);
    }

    /**
     * @param string $method
     * @param string|UriInterface $uri
     * @param array $headers
     * @param string|StreamInterface|null $body
     *
     * @return RequestInterface
     */
    protected function createRequest(string $method, $uri, array $headers = [], $body = null): RequestInterface
    {
        if ($this->requestFactory instanceof RequestFactory) {
            return $this->requestFactory->createRequest(
                $method,
                $uri,
                $headers,
                $body
            );
        }

        if (is_string($body) && '' !== $body && null === $this->streamFactory) {
            throw new \RuntimeException('Cannot create request: A stream factory is required to create a request with a non-empty string body.');
        }

        $request = $this->requestFactory->createRequest($method, $uri);

        foreach ($headers as $key => $value) {
            $request = $request->withHeader($key, $value);
        }

        if (null !== $body && '' !== $body) {
            $request = $request->withBody(
                is_string($body) ? $this->streamFactory->createStream($body) : $body
            );
        }

        return $request;
    }

    private function createUri(
        string $operationHost,
        string $resourcePath,
        array $queryParams
    ): UriInterface {
        $parsedUrl = parse_url($operationHost);

        $host = $parsedUrl['host'] ?? null;
        $scheme = $parsedUrl['scheme'] ?? null;
        $basePath = $parsedUrl['path'] ?? null;
        $port = $parsedUrl['port'] ?? null;
        $user = $parsedUrl['user'] ?? null;
        $password = $parsedUrl['pass'] ?? null;

        $uri = $this->uriFactory->createUri($basePath . $resourcePath)
            ->withHost($host)
            ->withScheme($scheme)
            ->withPort($port)
            ->withQuery(ObjectSerializer::buildQuery($queryParams));

        if ($user) {
            $uri = $uri->withUserInfo($user, $password);
        }

        return $uri;
    }
}
